export const testimonials ={
    name:'testimonials',
    title:'Testimonials',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'company',
            title:'Company',
            type:'string'
        },
        {
            name:'imageurl',
            title:'imgURL',
            type:'image',
            options:{
                hotshop:true,

            }
        },
        {
            name:'feedback',
            title:'Feedback',
            type:'string'
        },
    ],
}